[package]
authors = ["Bryant Luk <code@bryantluk.com>"]
categories = ["encoding", "no-std"]
description = "A Bencode encoding/decoding implementation."
documentation = "https://docs.rs/bt_bencode/"
edition = "2018"
include = [
  "/src",
  "/tests",
  "/Cargo.toml",
  "/CHANGELOG.md",
  "/clippy.toml",
  "/deny.toml",
  "/LICENSE-APACHE",
  "/LICENSE-MIT",
  "/README.md",
]
keywords = ["bencode", "bittorrent", "torrent", "serialization", "serde"]
license = "MIT OR Apache-2.0"
name = "bt_bencode"
readme = "README.md"
repository = "https://github.com/bluk/bt_bencode"
rust-version = "1.36.0"
version = "0.8.2"

[dependencies]
itoa = {version = "1.0.0", default-features = false }
serde = {version = "1.0.100", default-features = false }

[dev-dependencies]
serde_derive = "1.0.100"
sha1 = "0.11.0"

[features]
default = ["std"]

std = ["serde/std"]

alloc = ["serde/alloc"]

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]
