[licenses]
unlicensed = "deny"
allow = [
    "MIT",
    "Apache-2.0",
]
copyleft = "warn"
default = "deny"
exceptions = [
    { allow = ["MIT", "Apache-2.0", "Unicode-DFS-2016"], name = "unicode-ident", version = "1" },
]

[bans]
multiple-versions = "warn"
wildcards = "allow"