name: Rust Security Audit

permissions:
  contents: read

on:
  push:
    paths:
      - '**/Cargo.toml'
      - '**/Cargo.lock'
  pull_request:

jobs:
  audit:
    strategy:
      matrix:
        os:
          - ubuntu-latest
        rust:
          - stable
    runs-on: ${{ matrix.os }}
    steps:
      - name: Install toolchain
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ matrix.rust }}
          components: rustfmt
      - name: Rust Version
        run: rustc --version
      - run: cargo install cargo-audit
      - name: Checkout sources
        uses: actions/checkout@v3
        with:
          persist-credentials: false
      - run: cargo generate-lockfile
      - run: cargo audit --deny warnings